version: "3.5"

services:
  infini-elasticsearch-proxy:
    build:
       context: .
       dockerfile: ./Dockerfile
      
    ports:
      - 9000:9000
    container_name: "infini-elasticsearch-proxy"
    volumes:
      - ../:/go/src/infini.sh/proxy
      - ./entrypoint.sh:/entrypoint.sh

volumes:
  dist: